[package]
name = "digit-rec"
version = "0.1.0"
authors = ["Theodore DeRego <tderego94@gmail.com>"]

[dependencies]
deeplearn = { git = "https://github.com/tedsta/deeplearn-rs" }
gpuarray = { git = "https://github.com/tedsta/gpuarray-rs" }
rmp = "^0.7"
image = "*"
